---
driver:
  name: dokken
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: centos-7
    driver:
      image: centos:latest
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts net-tools

  - name: centos-6

verifier:
  name: inspec

suites:
  - name: dev
    run_list:
      - recipe:[java::default]
    attributes: { 'java': { 'jdk_version': '11'} }
    driver_config:
      ports:
        - 8080:80
    excludes: centos-6

  - name: prod
    driver:
      run_command: /sbin/init
    run_list:
      - recipe[java::default]
    attributes: { 'java': { 'jdk_version': '8' } }
    driver_config:
      ports:
        - 8081:80
    includes: centos-6
